# Generated by Django 6.0.5 on 2026-06-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('task_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('holiday', 'Holiday'), ('leave', 'Leave')], default='present', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.employee')),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'unique_together': {('date', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to='core.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='core.project')),
            ],
            options={
                'ordering': ['employee__name', 'project__code'],
                'unique_together': {('employee', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.project')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hours', to='core.timesheetentry')),
            ],
            options={
                'unique_together': {('entry', 'project')},
            },
        ),
    ]
